export default {
  fonts: {
    inter: 'Inter',
  },
  colors: {
    white: '#ffffff',
    bluewood: '#2B3253',
    eastBay: '#545C99',
    pacificBlue: '#00CFCF',
    persimon: '#FF6F4D',
    orange: '#FF9E4B',
    goldeRod: '#FFCE6C',
    oasis: '#FFF2D7',
    starDust: '#949492',
    grayNickel: '#BFBFBD',
    quillGray: '#DEDEDB',
    desertStorm: '#EDEDEA',
    pampas: '#FAFAF7',
    springWood: '#FCFCF9',
    mojo: '#BE4E34',
    mojoSmooth: '#F9EDEB',
    green: '#72D18D',
    greenSmooth: '#E8F8ED',
    mirage: '#1D2135',
  },
  weights: {
    regular: 400,
    medium: 500,
    semiBold: 600,
    bold: 700,
  },
  zIndex: {
    background: -10,
    default: 0,
    foreground: 10,
    dropdown: 25,
    modal: 50,
  },
};
